In [3]:
# @title
from google.colab import files

uploaded = files.upload()

file_name = None
if uploaded:
  for fn in uploaded.keys():
    print(f'Fichier "{fn}" téléchargé.')
    file_name = fn
else:
  print("Aucun fichier n'a été téléchargé. Veuillez le télécharger manuellement ou exécuter cette cellule à nouveau.")
  # @title
import pandas as pd
df = pd.read_csv('data.csv')

Saving data.csv to data.csv
Fichier "data.csv" téléchargé.

In [4]:
# @title
df.price_paid = df.price_paid.apply(lambda x: x.replace('$', ''))
df.price_paid = df.price_paid.astype(float)

In [5]:
df['price_paid'].mean().round(2)

np.float64(6.46)

In [6]:
df['price_paid'].sum()

np.float64(6461.93)

In [ ]:
df['price_paid'].min()

In [ ]:
df['price_paid'].max()

In [ ]:
df['price_paid'].unique()

In [ ]:
df['country'].value_counts()

In [ ]:
df['gender'].value_counts(normalize=True).round(2)

In [7]:
df.groupby('gender')['price_paid'].mean().round(2)

gender
Female    6.42
Male      6.47
Name: price_paid, dtype: float64

In [14]:
df.groupby(['gender', 'country'])['price_paid'].mean().round(2)

gender  country
Female  Canada           6.42
        France           6.35
        Morocco          7.02
        United States    6.44
Male    Canada           6.12
        France           6.50
        Morocco          6.15
        United States    6.67
Name: price_paid, dtype: float64